Layout:
  FrozenStringLiteralComment:
    Enabled: true
  ConditionalAssignment:
    Enabled: false
  StringLiterals:
    Enabled: false
  TrailingEmptyLines:
    Enabled: false
  LineLength:
    Max: 120
  UnusedMethodArgument:
    Enabled: false
  EmptyLines:
    Enabled: false
  RedundantReturn:
    Enabled: false
  RegexpLiteral:
    Enabled: false
  GuardClause:
    Enabled: false
  WordArray:
    Enabled: false
  SymbolProc:
    Enabled: false
  AbcSize:
    Enabled: false
  MutableConstant:
    Enabled: false
  SignalException:
    Enabled: false
  CyclomaticComplexity:
    Enabled: false
  MissingRespondToMissing:
    Enabled: false
Security/Open:
  Enabled: false
Documentation:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  Exclude:
    - '**/Rakefile'
    - '**/spec/**/*'
    - '**/db/schema.rb'
    - '**/bin/**'
    - '**config/**'
    - '**test/**'
